adding post submit v2
bloXroute-Labs/solana-trader-client-ts pull request #80
Opened 2023-12-13 19:04 UTC by tinystarinagalaxy

2023-12-13 20:12 UTC, atulsriv approved these changes

2023-12-21 20:27 UTC, DimaCantemir requested changes
you used postSubmit in the GRPC provider, fix that and we can merge

2023-12-21 20:27 UTC, DimaCantemir commented on bxsolana/provider/grpc.ts
> +        return this.client.postSubmit(request)
postSubmitV2 ?

2023-12-21 20:30 UTC, DimaCantemir approved these changes

2023-12-21 20:31 UTC, merged