TRAD898 - add support in providers for bundling
bloXroute-Labs/solana-trader-client-ts pull request #93
Opened 2024-01-29 20:21 UTC by atulsriv

2024-02-07 00:10 UTC, DimaCantemir requested changes

2024-02-07 00:10 UTC, DimaCantemir commented on bxsolana/utils/bundletip.ts
> +const TRADER_API_TIP_WALLET = "AFT8VayE7qr8MoQsW3wHsDS83HhEvhGWdbNSHRKeUDfQ"
I would not hardcode the but Document it and let the user get the most fresh one from our Docs.

2024-02-13 15:42 UTC, tinystarinagalaxy approved these changes

2024-02-13 18:22 UTC, DimaCantemir approved these changes

2024-02-13 18:33 UTC, merged